name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Flask
        run: pip install flask

      - name: Check Python application
        run: python -m py_compile app.py

      - name: Build Docker image
        run: docker build -t ci-cd-app .
